# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
